
package veriyapilari;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class hesaplama<T> extends javax.swing.JFrame {

    DefaultComboBoxModel dcm;
    BufferedReader input = null;
    File file;
    LinkedList equation1;
    LinkedList equation2;
    int x;

    /**
     * Creates new form hesaplama
     */
    public hesaplama() {
        initComponents();
        equation1 = new LinkedList();
        equation2 = new LinkedList();
        dcm = new DefaultComboBoxModel();
        dcm.addElement("+");
        dcm.addElement("-");
        cmbIslemler.setModel(dcm);
        cmbIslemler.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDosyaOku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDenklemler = new javax.swing.JTextArea();
        lblDenklemler = new javax.swing.JLabel();
        btnHesapla = new javax.swing.JButton();
        cmbIslemler = new javax.swing.JComboBox<>();
        txtSonucDenklem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSonucDenklem1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(527, 457));
        setMinimumSize(new java.awt.Dimension(527, 457));

        btnDosyaOku.setText("DOSYA OKU");
        btnDosyaOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosyaOkuActionPerformed(evt);
            }
        });

        txtDenklemler.setColumns(20);
        txtDenklemler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDenklemler.setRows(5);
        jScrollPane1.setViewportView(txtDenklemler);

        lblDenklemler.setText("Denklemler:");

        btnHesapla.setText("HESAPLA");
        btnHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHesaplaActionPerformed(evt);
            }
        });

        txtSonucDenklem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setText("Sonuç Denklemi");

        txtSonucDenklem1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setText("İşlem Sonucu:");

        jLabel3.setText("İşlem:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(btnDosyaOku)
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDenklemler)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSonucDenklem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSonucDenklem1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(15, 15, 15)
                        .addComponent(cmbIslemler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btnHesapla)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnDosyaOku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDenklemler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbIslemler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHesapla))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSonucDenklem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSonucDenklem1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDosyaOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosyaOkuActionPerformed
        equation1.clear();
        equation2.clear();
        txtDenklemler.setText("");
        txtSonucDenklem.setText("");
        txtSonucDenklem1.setText("");
        JFileChooser jFileChooser = new JFileChooser();
        int result = jFileChooser.showOpenDialog(this);
        try {
            file = jFileChooser.getSelectedFile();
            if (file != null) {
                input = new BufferedReader(new FileReader(file));
                String equation;
                int count = 0;
                while ((equation = input.readLine()) != null) {
                    switch (count) {
                        case 0:
                            txtDenklemler.setText(txtDenklemler.getText() + equation + "\n");
                            String[] terms = equation.split("\\+|(?=\\-)");
                            for (String term : terms) {
                                if (term.contains("x^") && !term.split("x\\^")[0].equals("")) {
                                    equation1.addLast(Integer.parseInt(term.split("x\\^")[0]),
                                            Integer.parseInt(term.split("x\\^")[1]));
                                } else if (term.contains("x^") && term.split("x\\^")[0].equals("")) {
                                    equation1.addLast(1,Integer.parseInt(term.split("x\\^")[1]));
                                } else if (!term.contains("x")) {
                                    equation1.addLast(Integer.parseInt(term), 0);
                                } else if (term.contains("x") && !term.contains("^")) {
                                    equation1.addLast(1, Integer.parseInt(term.split("x")[0]));
                                }
                            }
                            break;
                        case 1:
                            txtDenklemler.setText(txtDenklemler.getText() + equation + "\n");
                            terms = equation.split("\\+|(?=\\-)");
                            for (String term : terms) {
                                if (term.contains("x^")) {
                                    equation2.addLast(Integer.parseInt(term.split("x\\^")[0]), Integer.parseInt(term.split("x\\^")[1]));
                                } else if (!term.contains("x")) {
                                    equation2.addLast(Integer.parseInt(term), 0);
                                } else if (term.contains("x") && !term.contains("^")) {
                                    equation2.addLast(1, Integer.parseInt(term.split("x")[0]));
                                }
                            }
                            break;
                        case 2:
                            x = Integer.parseInt(equation);
                            txtDenklemler.setText(txtDenklemler.getText() + x);
                            break;
                    }
                    count++;
                }
                if (equation1.head != null && equation2.head != null) {
                    BufferedWriter list1 = new BufferedWriter(new FileWriter("list1.txt"));
                    BufferedWriter list2 = new BufferedWriter(new FileWriter("list2.txt"));
                    list1.write(equation1.string());
                    list1.close();
                    list2.write(equation2.string());
                    list2.close();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Dosya okunamadı. Tekrar deneyiniz.");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(hesaplama.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(hesaplama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDosyaOkuActionPerformed

    private void btnHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHesaplaActionPerformed
        // TODO add your handling code here:
        boolean seciliMi1 = true, secilimi2 = true;
        if (cmbIslemler.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen bir işlem seçiniz.");
            seciliMi1 = false;
        }
        if (txtDenklemler.getText().length() <= 0) {
            JOptionPane.showMessageDialog(this, "Lütfen bir dosya seçiniz.");
            secilimi2 = false;
        }
        if (seciliMi1 && secilimi2) {
            if (cmbIslemler.getSelectedItem().equals("+")) {
                LinkedList newEquation = equation1.addLinkedList(equation2);
                newEquation.simplification();
                Node temp = newEquation.head;
                txtSonucDenklem.setText(newEquation.toString());
                BigInteger sayi = new BigInteger("0");
                for (int i = 0; i < newEquation.getSize(); i++) {
                    BigInteger katSayi = new BigInteger(temp.data1.toString());
                    BigInteger taban = new BigInteger(x + "");
                    sayi = sayi.add(katSayi.multiply(taban.pow((int) temp.data2)));
                    temp = temp.next;
                }
                txtSonucDenklem1.setText(sayi.toString());
            }
            if (cmbIslemler.getSelectedItem().equals("-")) {
                LinkedList newEquation = equation1.subLinkedList(equation2);
                newEquation.simplification();
                Node temp = newEquation.head;
                txtSonucDenklem.setText(newEquation.toString());
                BigInteger sayi = new BigInteger("0");
                for (int i = 0; i < newEquation.getSize(); i++) {
                    BigInteger katSayi = new BigInteger(temp.data1.toString());
                    BigInteger taban = new BigInteger(x + "");
                    sayi = sayi.add(katSayi.multiply(taban.pow((int) temp.data2)));
                    temp = temp.next;
                }
                txtSonucDenklem1.setText(sayi.toString());
            }
        }
    }//GEN-LAST:event_btnHesaplaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new hesaplama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDosyaOku;
    private javax.swing.JButton btnHesapla;
    private javax.swing.JComboBox<String> cmbIslemler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDenklemler;
    private javax.swing.JTextArea txtDenklemler;
    private javax.swing.JTextField txtSonucDenklem;
    private javax.swing.JTextField txtSonucDenklem1;
    // End of variables declaration//GEN-END:variables
}
